### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by vitobasso** [theodi/csvhub#9]
Tried the extension but nothing happens :/
It shows up in chrome://extensions/ but nothing happens when I browse csv merges in github.

I can see the tabular UI (from normal github) here
https://github.com/theodi/test-data/blob/master/data.csv

But I only see text there, where I expected to see the UI from csvhub
https://github.com/theodi/test-data/commit/9f391e6e35963b96aa0eed56c20ccd70f326e1f7

Chrome version: 42.0.2311.90 m

Please let me know how can I find more helpful details.

**Comment by vitobasso** [comment]
got this in Chome's console:

Uncaught Error: CSVDataError: Illegal Quote [Row:1][Col:1](anonymous function) @ jquery.csv-0.71.js:570$.csv.parsers.parseEntry @ jquery.csv-0.71.js:501$.csv.toArray @ jquery.csv-0.71.js:618(anonymous function) @ csvhub.js:21

**Comment by akshetpandey** [comment]
Is this project dead?

**Comment by Floppy** [comment]
Not dead, but not getting a lot of time spent on it as it was only ever really a prototype. I admit I hadn't actually noticed this issue, sorry about that; I was away and ignoring all my email at the time! I might have chance to look into it in a couple of weeks, but if anyone else has time before I do, I'll happily merge PRs.

**Comment by nathanv** [comment]
@Floppy any updates?

**Comment by Floppy** [comment]
I've not had chance yet unfortunately. It's becoming obvious that more and more people are actually using this tool though (to my great surprise), so I'll try to get it fixed soon!

**Comment by htmldoug** [comment]
Thanks for the update. I'm also interested in using this.

**Comment by csrvermaak** [comment]
Having the same issue here - would love to be able to use this tool! Thanks :-)

**Comment by nathanv** [comment]
@Floppy Bump! :D.

**Comment by Floppy** [comment]
Apologies for the delay on this. Github had just changed the CSS selectors again. I've got it working again and uploaded a new version. You should get it through autoupdate soon.

**Comment by htmldoug** [comment]
Thanks @Floppy! Looking forward to testing it out.

**Comment by csrvermaak** [comment]
Great stuff, thanks @Floppy , it works again :)
